### PR TITLE
Feature/conditional block

### PR DESCRIPTION
**Pull request by wesen**
I'm writing a compiler, and for efficiency purposes (and also template "clarity", in that i can see when a conditional is meant rather than iteration/lambda/new context/conditional), I decided to add a {{?test}} construct that can be used for conditionals. Also allows a kind of shortcut syntax {{?test}}then{{^test}}else{{/test}}.

let me know what you think.

### CODE REVIEW

**Comment by urzds** [comment]
It appears that d5c6d4e does not belong into this pull request.

**Comment by urzds** [comment]
What was the reason for closing this?

**Comment by wesen** [comment]
Just closing after 5 years to clean up my open pull request view :)

**Comment by urzds** [comment]
Shall I submit the patch in a new pull request?

**Comment by wesen** [comment]
Sure, go ahead. I’m happy to reopen the pull-requests too  if that is easier?

**Comment by urzds** [comment]
That would probably be easier, yes. Are you still maintaining the specification and do you plan to make changes like these?

**Comment by wesen** [comment]
Oh I’m not the maintainer of mustache, and in fact I haven’t done any web development in the last 5 years. I don’t see myself working on this any time in the future either.

**Pull request closed without merging**
