### PR TITLE
Allow iterating over implicit iterators.

### PR DESCRIPTION
**Pull request by bobthecow**
Implicit iterators should be treated just like
explicit tags, i.e. they should work for iterating
over nested arrays.

    {{#items}}
      {{#.}}
        {{.}}
      {{/.}}
    {{/items}}

See mustache/mustache#177

### CODE REVIEW

**Comment by locks** [comment]
:dancers: :dancer: :dancers:

**Comment by dasilvacontin** [comment]
:shipit:

**Comment by ianka** [comment]
Spec is still at version 1.1.2. Shouldn't it have been incremented?

**Comment by bobthecow** [comment]
Yeah, it looks like nobody tagged a release for this. It should prolly be tagged as 1.1.3.

@locks can you do that?

**Comment by locks** [comment]
https://github.com/mustache/spec/releases/tag/v1.1.3 @bobthecow @ianka :+1: ?

**Comment by bobthecow** [comment]
:+1:

Was that already there, or is GitHub's tag page just intentionally confusing?

**Comment by locks** [comment]
Nope, just added it right now

**Comment by ianka** [comment]
I have updated mustache.tcl's version right now, thanks.

**Pull request merged**
