### PR TITLE
Pretty print JSON files, and terminate with newline

### PR DESCRIPTION
**Pull request by softmoth**
Text files that don't end with a newline can be troublesome or unacceptable in some contexts.

The only down side is a bit of merging hassle for existing pull requests. But that happens anyways, and of course the YAML file is authoritative so JSON conflicts can be ignored in practice.

### CODE REVIEW

**Comment by gasche** [comment]
Looks fine to me.

(It would also be nice to have some kind of human-friendlier printing of the generated JSON, because currently it is painful for implementations that use the JSON to locate the source of a test failure within the big generated one-liner.)

**Comment by softmoth** [comment]
Yes, @gasche, good point. I found how to do that. Its default looks pretty good, I think.

**Comment by gasche** [comment]
Very nice! Thanks.

**Comment by Danappelxx** [comment]
I'm a tiny bit hesitant to merge this since all other pull requests would need to be re-run. I'll merge a few and then come back to this one.

**Comment by Danappelxx** [comment]
I am very much in favor of the quality-of-life and readability improvement this provides! I merged a few active pull requests, can you go ahead and re-generate the json?

**Comment by softmoth** [comment]
I force-pushed an update of the `specs/*.json` files.

**Comment by Danappelxx** [comment]
Thanks!

**Pull request merged**
